# Generated by Django 3.0.5 on 2020-04-23 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, null=True)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=140, null=True)),
                ('user_type', models.CharField(default='RBT', max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('alias', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('dry_checks', models.BooleanField(default=False)),
                ('underwear', models.BooleanField(default=True)),
                ('positive_practice', models.BooleanField(default=False)),
                ('liquid_intake', models.BooleanField(default=False)),
                ('current_voids', models.IntegerField(default=0)),
                ('current_accidents', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=0)),
                ('total_voids', models.IntegerField(default=0)),
                ('total_accidents', models.IntegerField(default=0)),
                ('trainers', models.ManyToManyField(to='toilet_training.Profile')),
            ],
        ),
    ]
